[[stack]]
name = "bezel-agent"
description = "bezel agent stack"
deploy = true
tags = ["prod"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/beszel/agent"


[[stack]]
name = "bezel-hub"
description = "bezel hub stack"
deploy = true
tags = ["prod"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/beszel/hub"