[[stack]]
name = "bezel-agent"
description = "bezel agent stack"
deploy = true
tags = ["monitoring"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/beszel/agent"
environment = """
BEZEL_PUBLIC_KEY=[[BEZEL_PUBLIC_KEY_node4]]
BEZEL_TOKEN=[[BEZEL_TOKEN_node4]]
BEZEL_HUB_URL=[[BEZEL_HUB_URL]]
"""

[[stack]]
name = "bezel-hub"
description = "bezel hub stack"
deploy = true
tags = ["monitoring"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/beszel/hub"

[[stack]]
name = "uptime-kuma"
description = "uptime kuma stack"
deploy = true
tags = ["monitoring"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/uptime-kuma"


[[stack]]
name = "npm"
description = "nginx proxy manager stack"
deploy = true
tags = ["ingress"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/npm"

[[stack]]
name = "crafty-controller"
description = "crafty controller stack"
deploy = true
tags = ["minecraft"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/crafty-controller"

[[stack]]
name= "auth"
description = "authentication stack"
deploy = true
tags = ["authentication"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/auth"
environment = """
TINYAUTH_APPURL=[[TINYAUTH_APPURL]]
TINYAUTH_AUTH_USERS=[[TINYAUTH_AUTH_USERS]]
POCKET_ID_APP_URL=[[POCKET_ID_APP_URL]]
POCKET_ID_ENCRYPTION_KEY=[[POCKET_ID_ENCRYPTION_KEY]]
TINYAUTH_POCKETID_CLIENTID=[[TINYAUTH_POCKETID_CLIENTID]]
TINYAUTH_POCKETID_CLIENTSECRET=[[TINYAUTH_POCKETID_CLIENTSECRET]]
"""


[[stack]]
name = "mc-server"
description = "minecraft server stack"
deploy = true
tags = ["game-server", "minecraft"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/mc"

[[stack]]
name = "backup"
description = "backup stack"
deploy = true
tags = ["backup"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/backup"

[[stack]]
name = "access"
description = "access stack"
deploy = true
tags = ["access"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/access"
environment = """
WG_OIDC_CLIENT_SECRET=[[WG_OIDC_CLIENT_SECRET]]
"""