[[stack]]
name = "bezel-agent"
description = "bezel agent stack"
deploy = true
tags = ["prod"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/beszel/agent"
environment = """
BEZEL_PUBLIC_KEY=[[BEZEL_PUBLIC_KEY]]
BEZEL_TOKEN=[[BEZEL_TOKEN]]
BEZEL_HUB_URL=[[BEZEL_HUB_URL]]
"""


[[stack]]
name = "bezel-hub"
description = "bezel hub stack"
deploy = true
tags = ["prod"]
[stack.config]
server = "node4"
repo = "Evan-2007/lab"
branch = "main"
run_directory = "./komodo/stacks/beszel/hub"