
services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        environment:
            - TZ=Etc/UTC
        ports:
            - "8443:8443" # HTTPS
            - "8123:8123" # DYNMAP
            - "19132:19132/udp" # BEDROCK
            - "25566-25600:25566-25600" # MC SERV PORT RANGE
        volumes:
            - crafty_backups:/crafty/backups
            - crafty_logs:/crafty/logs
            - crafty_servers:/crafty/servers
            - crafty_config:/crafty/app/config
            - crafty_import:/crafty/import

volumes:
    crafty_backups:
    crafty_logs:
    crafty_servers:
    crafty_config:
    crafty_import: