services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/sda:/dev/sda:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BEZEL_PUBLIC_KEY}
      HUB_URL: ${BEZEL_HUB_URL}
      TOKEN: ${BEZEL_TOKEN}
    cap_add:
    - SYS_RAWIO # required for S.M.A.R.T. data
    - SYS_ADMIN # required for NVMe S.M.A.R.T. data