---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
  namespace: pocket-id
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    instance:
      name: pocket-id
      serviceMonitor:
        enabled: false
      spec:
        image: ghcr.io/pocket-id/pocket-id:v2.13.0-distroless
        appUrl: https://id.${DOMAIN_PUBLIC}
        encryptionKey:
          valueFrom:
            secretKeyRef:
              name: pocket-id
              key: ENCRYPTION_KEY
        persistence:
          enabled: true
          storageClass: truenas-iscsi
          accessModes: [ReadWriteOnce]
          size: 1Gi
        metrics:
          enabled: true      