apiVersion: v1
kind: Secret
metadata:
    name: pocket-id
    namespace: pocket-id
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:kHZPIecNKR09p3bjFO2PlcW0XCuBdcsaJSjlSYyz+K6AMDfnoIcItBfssbc=,iv:FmXGUPN0nbzZO20w+P+M2F0JSFPZcpeau4bpHR7LLJM=,tag:YFk/1nNVTeuBK2lkKZFkww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVUhCQ1JnTEJRczhlS2Ro
            K1ZzL2FqVXQ3NE0wR3QrS2lSNmlQbW9xVkMwCjlnaDBtMUZxTEs4VzV2SXk3cm9n
            WE9MamphNkt5Z1creEdkOS83UXpDYmsKLS0tIDUvdnJwV242UmRXVXBGYXEvemlN
            MFBnUVdVMm13by8wNlJPcFFTYmRNU1EKYPMrrG7lBFMu+wcNZPrpAw8qW2nefzmi
            bR6DQUSGj35GYZJJFd5GtKTvJsvH6N9wb4T6iBLIILtN8ISUcPYVnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1306vmgtph4w0ttdgxvp5lkn90da632qandaad2875hg0hrn9yfsqmta89v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T05:16:37Z"
    mac: ENC[AES256_GCM,data:rZqfS6f2oWz6R/gKFv9zYcq/zdYZ92Yj6+aNkbEjXEryO2QHTemUa5trpCioLYABNu4DQhcPY7n8R/VzBfw1qbfeaYRfCVsqMonO9w0dnQa5n03NZNlyAWsO/CiTc186czA6UGToVEeVfRZhy6YDuZJCntIfLGAzbgwckdZR8sk=,iv:xLWQEfW3H5xM7/K3FxhK9T7jKX/PV1Y1N3OltKaiquo=,tag:BZs+GO8R60nOHgI97nTiEA==,type:str]
    version: 3.13.3
